// <auto-generated />
namespace DLL.Methods.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initials56 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initials56));
        
        string IMigrationMetadata.Id
        {
            get { return "201707120734549_initials56"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
