// <auto-generated />
namespace DLL.Methods.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createInitial3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createInitial3));
        
        string IMigrationMetadata.Id
        {
            get { return "201707051322269_createInitial3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
